image: "hakutyou/ubuntu:tuna"

stages:
  - build
  - deploy

before_script:
  - echo "准备"

build_master:
  stage: build
  script:
    - echo "build"
  only:
    - master

deploy_master:
  stage: deploy
  script:
    - echo "deploy"
  only:
    - master

