version: '3'

networks:
  base-net:
    external: true

services:
  api:
    image: hakutyou/python3:python3
    restart: always
    hostname: api
    working_dir: /app/api
    # command: tail -f /dev/null
    command: ./run.sh
    volumes:
      - ${HOME}/.pip/pip.conf:/root/.pip/pip.conf:ro
      - ./:/app/api/
    networks:
      base-net:
        ipv4_address: 172.18.0.71

