version: '3'

networks:
  base-net:
    external: true

services:
  api:
    image: hakutyou/python3:python3
    restart: always
    hostname: api
    command: ./run.sh
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - /etc/gshadow:/etc/gshadow:ro
      - ./:/app/
    networks:
      base-net:
        ipv4_address: 172.18.0.70

  celery:
    image: hakutyou/python3:python3
    restart: always
    hostname: celery
    command: ./script/celery.sh
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - /etc/gshadow:/etc/gshadow:ro
      - .:/app
    networks:
      base-net:
        ipv4_address: 172.18.0.71

