# Generated by Django 2.2.7 on 2019-11-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictKanaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=64, unique=True, verbose_name='かな')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'かな表',
                'verbose_name_plural': 'かな表',
                'db_table': 'dict_kana_table',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DictKanjiItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(default=None, max_length=64, unique=True, verbose_name='漢字')),
                ('imi', models.CharField(default=None, max_length=256, verbose_name='意味')),
                ('theta', models.FloatField(default=1.0, verbose_name='シータ')),
                ('hinnsi', models.CharField(max_length=64, verbose_name='品词')),
                ('rei', models.TextField(verbose_name='例')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('kana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kanji', to='record.DictKanaItem')),
            ],
            options={
                'verbose_name': '漢字表',
                'verbose_name_plural': '漢字表',
                'db_table': 'dict_kanji_table',
            },
        ),
        migrations.CreateModel(
            name='DictDougi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dougi', models.CharField(max_length=256, verbose_name='説明')),
                ('rei', models.TextField(verbose_name='例')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='更新时间')),
                ('imi', models.ManyToManyField(related_name='dougi', to='record.DictKanjiItem')),
            ],
            options={
                'verbose_name': '同義語表',
                'verbose_name_plural': '同義語表',
                'db_table': 'dict_dougi_table',
            },
        ),
        migrations.CreateModel(
            name='DictScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date', models.DateField(auto_now_add=True, verbose_name='次回の時間')),
                ('score', models.CharField(max_length=128, verbose_name='アカウント点数')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.DictKanjiItem')),
            ],
            options={
                'verbose_name': 'アカウント点数表',
                'verbose_name_plural': 'アカウント点数表',
                'db_table': 'dict_score_table',
                'unique_together': {('account', 'kanji')},
            },
        ),
    ]
