# Generated by Django 2.2.7 on 2019-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictdougi',
            name='dougi',
            field=models.CharField(default='', max_length=256, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='dictdougi',
            name='rei',
            field=models.TextField(default='', verbose_name='例'),
        ),
        migrations.AlterField(
            model_name='dictkanjiitem',
            name='imi',
            field=models.CharField(default='', max_length=256, verbose_name='意味'),
        ),
        migrations.AlterField(
            model_name='dictkanjiitem',
            name='kanji',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='漢字'),
        ),
        migrations.AlterField(
            model_name='dictscore',
            name='score',
            field=models.CharField(default='', max_length=128, verbose_name='アカウント点数'),
        ),
    ]
