# Generated by Django 2.2.7 on 2019-11-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20191119_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictscore',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='record.DictKanjiItem'),
        ),
        migrations.AlterField(
            model_name='dictscore',
            name='next_date',
            field=models.DateField(verbose_name='次回の時間'),
        ),
    ]
