# Generated by Django 2.2.7 on 2020-04-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20191120_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictkanjiitem',
            name='hinnsi',
            field=models.CharField(choices=[('meisi', '名詞'), ('dousi', '動詞')], max_length=64, verbose_name='品词'),
        ),
    ]
